### ISSUE TITLE
NABU loading issue when responding to 0x8F request

### ISSUE THREAD

**Issue by cml37** [hupshall/NabuAdaptor#1]
Building the latest source, I noticed that sending a 0xE4 in response to a 0x8F causes issues with any further cycle/segment loading.  Commenting out this offending line resolves the issue:
https://github.com/hupshall/NabuAdaptor/blob/770a0d5ff46967732a7ea8989e7415b9028122f8/Server.cs#L154

**Comment by hupshall** [comment]
All the other adapter implementations that I see also return 0xe4 on a response to 0x8f - and I have no issues - it may  be something else in your implementation?

**Comment by cml37** [comment]
@hupshall thanks for your response.  Very interesting!  I built the C# version and it crashed the emulator and the real NABU too.  But let me have another look!

**Comment by hupshall** [comment]
Nope, I found it - there should be a  this.ReadByte(); right before the write to 0xE4, that got removed.

**Comment by hupshall** [comment]
case 0x8F:
                                this.ReadByte();
                                this.WriteBytes(0xE4);
                                break;

**Comment by cml37** [comment]
Oh, awesome!!  Nice find there :)

**Comment by cml37** [comment]
Confirmed locally that this did the trick 🥳🥳🥳
