### ISSUE TITLE
Safeguard against trailing slash for passed in URL source

### ISSUE THREAD

**Issue by cml37** [hupshall/NabuAdaptor#2]
For this line:

https://github.com/hupshall/NabuAdaptor/blob/770a0d5ff46967732a7ea8989e7415b9028122f8/WebLoader.cs#L87

It may be worthwhile to "trim" the trailing slash in case the user specifies one, i.e. 

`directoryPath = path.Trim("/".ToCharArray());`

**Comment by hupshall** [comment]
yup, will do.
