### ISSUE TITLE
Potential Performance Improvement with Loader Usage

### ISSUE THREAD

**Issue by cml37** [hupshall/NabuAdaptor#3]
Regarding the loader instantiation: 
https://github.com/hupshall/NabuAdaptor/blob/770a0d5ff46967732a7ea8989e7415b9028122f8/Server.cs#L259

Since the loader won't change between iterations of segment loading, you might consider moving the loader outside of `handleFileRequest`.  Perhaps to a location such as this, prior to the "while" loop that reads bytes:
https://github.com/hupshall/NabuAdaptor/blob/770a0d5ff46967732a7ea8989e7415b9028122f8/Server.cs#L148

**Comment by hupshall** [comment]
So we only actually create and use the loader when the file is not in the cache, so for all subsequent calls into HandleFileRequest, all that code is bypassed.

**Comment by cml37** [comment]
Fair point!  Any non-cached segment will construct a new object, but, I agree with you: if settings are allowed to be changed between iterations of loading segments, then your approach is safer.  Thanks for having a look.
